[package]
name = "Flow"
version = "1.0.0"

[dependencies]
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "0eea6ffdca81b337e9b8e9922e4c6ee34459bfc0" }
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib/", rev = "0eea6ffdca81b337e9b8e9922e4c6ee34459bfc0" }

[addresses]
std = "0x1"
flow = "_"

[dev-addresses]
flow = "0xF"
