[package]
name = "Flow"
version = "1.0.0"

[dependencies]
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "23896f357ed5810744842a528e8060dd1200894b" }
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib/", rev = "23896f357ed5810744842a528e8060dd1200894b" }

[addresses]
std = "0x1"
flow = "_"

[dev-addresses]
flow = "0xF"
