[package]
name = "Flow"
version = "1.0.0"

[dependencies]
AptosStdlib = { git = "https://github.com/laminar-markets/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "f8c8cdf81cee7f75cc53743187a0aa5adc5cdeea" }
MoveStdlib = { git = "https://github.com/laminar-markets/aptos-core.git", subdir = "aptos-move/framework/move-stdlib/", rev = "f8c8cdf81cee7f75cc53743187a0aa5adc5cdeea" }

[addresses]
std = "0x1"
flow = "_"

[dev-addresses]
flow = "0xF"
