[package]
name = "Flow"
version = "1.0.0"

[dependencies]
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "60ff36e65c8cf0a58d50f0b5d97a2033af1b3144" }
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib/", rev = "60ff36e65c8cf0a58d50f0b5d97a2033af1b3144" }

[addresses]
std = "0x1"
flow = "_"

[dev-addresses]
flow = "0xF"
