[package]
name = "Flow"
version = "1.0.0"

[dependencies]
AptosStdlib = { git = "https://github.com/laminar-markets/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "0d52608519ce471f7ab495685c96db6baf83da0c" }
MoveStdlib = { git = "https://github.com/laminar-markets/aptos-core.git", subdir = "aptos-move/framework/move-stdlib/", rev = "0d52608519ce471f7ab495685c96db6baf83da0c" }

[addresses]
std = "0x1"
flow = "_"

[dev-addresses]
flow = "0xF"
