[package]
name = "Flow"
version = "1.0.0"

[dependencies]
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "37baa96123b547c4d6dd12caf074c37bd80d4b19" }
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib/", rev = "37baa96123b547c4d6dd12caf074c37bd80d4b19" }

[addresses]
std = "0x1"
flow = "_"

[dev-addresses]
flow = "0xF"