[package]
name = "Flow"
version = "1.0.0"

[dependencies]
AptosStdlib = { git = "https://github.com/laminar-markets/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "d49b500aa41eec55f957d8490cb10db8fb46b60c" }
MoveStdlib = { git = "https://github.com/laminar-markets/aptos-core.git", subdir = "aptos-move/framework/move-stdlib/", rev = "d49b500aa41eec55f957d8490cb10db8fb46b60c" }

[addresses]
std = "0x1"
flow = "_"

[dev-addresses]
flow = "0xF"
