[package]
name = "Flow"
version = "0.0.0"

[dependencies]
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "23aa41fdc3c5a2c1ee0175d29c639c7deffb4837" }
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib/", rev = "23aa41fdc3c5a2c1ee0175d29c639c7deffb4837" }

[addresses]
std = "0x1"
flow = "0xF"
